name: Create publications

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - data/publications.bib

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Python and dependencies
        uses: actions/setup-python@v5
        with:
          python-version: ">=3.11"
          cache: pip
      - run: pip install -r requirements.txt
     
      - name: Run script
        run: python scripts/bibtex_to_json.py data/publications.bib > data/publications.json

      - name: Collect `.bib` files
        run: cp /tmp/*.bib static/research/

      - name: Open pull request
        uses: peter-evans/create-pull-request@v8
        with:
          # This is deliberately conservative with respect to the files
          # that it suggests.
          add-paths: |
            data/publications.json
            static/research/*.bib
          branch: publications-update
          title: "Updated publications"
          commit-message: "Updated publications"
          body: >
            This is the automated output from `bibtex_to_json.py`. Make sure
            to review before merging.
          delete-branch: true
